spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P22C105?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S08P22C105@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
    password: UVatA2MtuY
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 3.38.101.15
      port: 6379
file:
  image:
    #    path: C:/Users/SSAFY/Desktop/storage/
    #    path: C:/Users/multicampus/Desktop/storage/
    #    path: /Users/bellroot/Desktop/storage/
    path: /Users/gayoungyang/Desktop/storage/
#    path: C:/Users/cba15/Desktop/storage/
oauth:
  kakao:
    redirectUri: http://localhost:8080/api/v1/oauth/kakao

OPENVIDU_URL: http://localhost:4443/