spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create
file:
  image:

#    path: C:/Users/SSAFY/Desktop/storage/
     path: C:/Users/multicampus/Desktop/storage/
#    path: /Users/bellroot/Desktop/storage/
#    path: /Users/gayoungyang/Desktop/storage/
#    path: C:/Users/cba15/Desktop/storage/
oauth:
  kakao:
    redirectUri: http://localhost:8080/api/v1/oauth/kakao

OPENVIDU_URL: http://localhost:4443/